apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadppwt5195-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadppwt5195-tenant-component
    app.kubernetes.io/part-of: loadppwt5195-tenant-app
  name: loadppwt5195-tenant-component
  namespace: loadppwt5195-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadppwt5195-tenant-component
    weight: null
status: {}
