apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadppwt5195-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadppwt5195-tenant-component
    app.kubernetes.io/part-of: loadppwt5195-tenant-app
  name: loadppwt5195-tenant-component
  namespace: loadppwt5195-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: loadppwt5195-tenant-component
status:
  loadBalancer: {}
